// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: rpc/masterrpc/master.proto

package masterrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MWhoAmIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State string `protobuf:"bytes,1,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *MWhoAmIResponse) Reset() {
	*x = MWhoAmIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_masterrpc_master_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MWhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MWhoAmIResponse) ProtoMessage() {}

func (x *MWhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_masterrpc_master_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MWhoAmIResponse.ProtoReflect.Descriptor instead.
func (*MWhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_rpc_masterrpc_master_proto_rawDescGZIP(), []int{0}
}

func (x *MWhoAmIResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type BasedMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuPercent       int64   `protobuf:"varint,1,opt,name=CpuPercent,proto3" json:"CpuPercent,omitempty"`
	MemUsage         int32   `protobuf:"varint,2,opt,name=MemUsage,proto3" json:"MemUsage,omitempty"`
	TotalMem         int32   `protobuf:"varint,3,opt,name=TotalMem,proto3" json:"TotalMem,omitempty"`
	MemUsedPercent   float32 `protobuf:"fixed32,4,opt,name=MemUsedPercent,proto3" json:"MemUsedPercent,omitempty"`
	DiskUsage        int64   `protobuf:"varint,5,opt,name=DiskUsage,proto3" json:"DiskUsage,omitempty"`
	TotalDisk        int64   `protobuf:"varint,6,opt,name=TotalDisk,proto3" json:"TotalDisk,omitempty"`
	DiskUsagePercent float32 `protobuf:"fixed32,7,opt,name=DiskUsagePercent,proto3" json:"DiskUsagePercent,omitempty"`
}

func (x *BasedMetrics) Reset() {
	*x = BasedMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_masterrpc_master_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasedMetrics) ProtoMessage() {}

func (x *BasedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_masterrpc_master_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasedMetrics.ProtoReflect.Descriptor instead.
func (*BasedMetrics) Descriptor() ([]byte, []int) {
	return file_rpc_masterrpc_master_proto_rawDescGZIP(), []int{1}
}

func (x *BasedMetrics) GetCpuPercent() int64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *BasedMetrics) GetMemUsage() int32 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *BasedMetrics) GetTotalMem() int32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *BasedMetrics) GetMemUsedPercent() float32 {
	if x != nil {
		return x.MemUsedPercent
	}
	return 0
}

func (x *BasedMetrics) GetDiskUsage() int64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *BasedMetrics) GetTotalDisk() int64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

func (x *BasedMetrics) GetDiskUsagePercent() float32 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

type JoinServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   string        `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // ip:port
	State string        `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
	Stats *BasedMetrics `protobuf:"bytes,3,opt,name=Stats,proto3" json:"Stats,omitempty"`
}

func (x *JoinServer) Reset() {
	*x = JoinServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_masterrpc_master_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinServer) ProtoMessage() {}

func (x *JoinServer) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_masterrpc_master_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinServer.ProtoReflect.Descriptor instead.
func (*JoinServer) Descriptor() ([]byte, []int) {
	return file_rpc_masterrpc_master_proto_rawDescGZIP(), []int{2}
}

func (x *JoinServer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *JoinServer) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JoinServer) GetStats() *BasedMetrics {
	if x != nil {
		return x.Stats
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerPool []*JoinServer `protobuf:"bytes,1,rep,name=ServerPool,proto3" json:"ServerPool,omitempty"`
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_masterrpc_master_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_masterrpc_master_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_rpc_masterrpc_master_proto_rawDescGZIP(), []int{3}
}

func (x *JoinResponse) GetServerPool() []*JoinServer {
	if x != nil {
		return x.ServerPool
	}
	return nil
}

var File_rpc_masterrpc_master_proto protoreflect.FileDescriptor

var file_rpc_masterrpc_master_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2f,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0f, 0x4d, 0x57, 0x68,
	0x6f, 0x41, 0x6d, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x22, 0xf6, 0x01, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x12, 0x26, 0x0a, 0x0e, 0x4d,
	0x65, 0x6d, 0x55, 0x73, 0x65, 0x64, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0e, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x64, 0x50, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x44, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x12,
	0x2a, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x61, 0x67, 0x65, 0x50, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x44, 0x69, 0x73, 0x6b, 0x55,
	0x73, 0x61, 0x67, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x22, 0x59, 0x0a, 0x0a, 0x4a,
	0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x23, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22, 0x3b, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x50, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50,
	0x6f, 0x6f, 0x6c, 0x32, 0x6b, 0x0a, 0x0d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x57, 0x68, 0x6f, 0x41, 0x6d, 0x49, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x4d, 0x57, 0x68, 0x6f, 0x41, 0x6d, 0x49,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x24, 0x0a, 0x04, 0x4a, 0x6f,
	0x69, 0x6e, 0x12, 0x0b, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a,
	0x0d, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x79, 0x75, 0x73, 0x68, 0x31, 0x38, 0x30, 0x32, 0x33, 0x2f, 0x4c, 0x6f, 0x61, 0x64, 0x5f, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x5f, 0x46, 0x79, 0x70, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rpc_masterrpc_master_proto_rawDescOnce sync.Once
	file_rpc_masterrpc_master_proto_rawDescData = file_rpc_masterrpc_master_proto_rawDesc
)

func file_rpc_masterrpc_master_proto_rawDescGZIP() []byte {
	file_rpc_masterrpc_master_proto_rawDescOnce.Do(func() {
		file_rpc_masterrpc_master_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_masterrpc_master_proto_rawDescData)
	})
	return file_rpc_masterrpc_master_proto_rawDescData
}

var file_rpc_masterrpc_master_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_masterrpc_master_proto_goTypes = []interface{}{
	(*MWhoAmIResponse)(nil), // 0: MWhoAmIResponse
	(*BasedMetrics)(nil),    // 1: BasedMetrics
	(*JoinServer)(nil),      // 2: JoinServer
	(*JoinResponse)(nil),    // 3: JoinResponse
	(*emptypb.Empty)(nil),   // 4: google.protobuf.Empty
}
var file_rpc_masterrpc_master_proto_depIdxs = []int32{
	1, // 0: JoinServer.Stats:type_name -> BasedMetrics
	2, // 1: JoinResponse.ServerPool:type_name -> JoinServer
	4, // 2: MasterService.WhoAmI:input_type -> google.protobuf.Empty
	2, // 3: MasterService.Join:input_type -> JoinServer
	0, // 4: MasterService.WhoAmI:output_type -> MWhoAmIResponse
	3, // 5: MasterService.Join:output_type -> JoinResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_masterrpc_master_proto_init() }
func file_rpc_masterrpc_master_proto_init() {
	if File_rpc_masterrpc_master_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_masterrpc_master_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MWhoAmIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_masterrpc_master_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasedMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_masterrpc_master_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_masterrpc_master_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_masterrpc_master_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_masterrpc_master_proto_goTypes,
		DependencyIndexes: file_rpc_masterrpc_master_proto_depIdxs,
		MessageInfos:      file_rpc_masterrpc_master_proto_msgTypes,
	}.Build()
	File_rpc_masterrpc_master_proto = out.File
	file_rpc_masterrpc_master_proto_rawDesc = nil
	file_rpc_masterrpc_master_proto_goTypes = nil
	file_rpc_masterrpc_master_proto_depIdxs = nil
}
