// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: rpc/carpc/ca.proto

package carpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CAWhoAmIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State string `protobuf:"bytes,1,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *CAWhoAmIResponse) Reset() {
	*x = CAWhoAmIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_carpc_ca_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CAWhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAWhoAmIResponse) ProtoMessage() {}

func (x *CAWhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_carpc_ca_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAWhoAmIResponse.ProtoReflect.Descriptor instead.
func (*CAWhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_rpc_carpc_ca_proto_rawDescGZIP(), []int{0}
}

func (x *CAWhoAmIResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type CAHealthMetricResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuPercent       int64   `protobuf:"varint,1,opt,name=CpuPercent,proto3" json:"CpuPercent,omitempty"`
	MemUsage         int32   `protobuf:"varint,2,opt,name=MemUsage,proto3" json:"MemUsage,omitempty"`
	TotalMem         int32   `protobuf:"varint,3,opt,name=TotalMem,proto3" json:"TotalMem,omitempty"`
	MemUsedPercent   float32 `protobuf:"fixed32,4,opt,name=MemUsedPercent,proto3" json:"MemUsedPercent,omitempty"`
	DiskUsage        int64   `protobuf:"varint,5,opt,name=DiskUsage,proto3" json:"DiskUsage,omitempty"`
	TotalDisk        int64   `protobuf:"varint,6,opt,name=TotalDisk,proto3" json:"TotalDisk,omitempty"`
	DiskUsagePercent float32 `protobuf:"fixed32,7,opt,name=DiskUsagePercent,proto3" json:"DiskUsagePercent,omitempty"`
}

func (x *CAHealthMetricResponse) Reset() {
	*x = CAHealthMetricResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_carpc_ca_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CAHealthMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAHealthMetricResponse) ProtoMessage() {}

func (x *CAHealthMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_carpc_ca_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAHealthMetricResponse.ProtoReflect.Descriptor instead.
func (*CAHealthMetricResponse) Descriptor() ([]byte, []int) {
	return file_rpc_carpc_ca_proto_rawDescGZIP(), []int{1}
}

func (x *CAHealthMetricResponse) GetCpuPercent() int64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *CAHealthMetricResponse) GetMemUsage() int32 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *CAHealthMetricResponse) GetTotalMem() int32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *CAHealthMetricResponse) GetMemUsedPercent() float32 {
	if x != nil {
		return x.MemUsedPercent
	}
	return 0
}

func (x *CAHealthMetricResponse) GetDiskUsage() int64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *CAHealthMetricResponse) GetTotalDisk() int64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

func (x *CAHealthMetricResponse) GetDiskUsagePercent() float32 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

type KeyPairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algorithm string `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Keyname   string `protobuf:"bytes,2,opt,name=keyname,proto3" json:"keyname,omitempty"`
}

func (x *KeyPairRequest) Reset() {
	*x = KeyPairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_carpc_ca_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPairRequest) ProtoMessage() {}

func (x *KeyPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_carpc_ca_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPairRequest.ProtoReflect.Descriptor instead.
func (*KeyPairRequest) Descriptor() ([]byte, []int) {
	return file_rpc_carpc_ca_proto_rawDescGZIP(), []int{2}
}

func (x *KeyPairRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *KeyPairRequest) GetKeyname() string {
	if x != nil {
		return x.Keyname
	}
	return ""
}

type KeyPairs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey  string `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PrivateKey string `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
}

func (x *KeyPairs) Reset() {
	*x = KeyPairs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_carpc_ca_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPairs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPairs) ProtoMessage() {}

func (x *KeyPairs) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_carpc_ca_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPairs.ProtoReflect.Descriptor instead.
func (*KeyPairs) Descriptor() ([]byte, []int) {
	return file_rpc_carpc_ca_proto_rawDescGZIP(), []int{3}
}

func (x *KeyPairs) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *KeyPairs) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

var File_rpc_carpc_ca_proto protoreflect.FileDescriptor

var file_rpc_carpc_ca_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x61, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x28, 0x0a, 0x10, 0x43, 0x41, 0x57, 0x68, 0x6f, 0x41, 0x6d, 0x49, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x80, 0x02, 0x0a, 0x16,
	0x43, 0x41, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x70, 0x75, 0x50, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x70, 0x75, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x12, 0x26,
	0x0a, 0x0e, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x64, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x64, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x6b, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x44, 0x69, 0x73, 0x6b, 0x55,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x69, 0x73,
	0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x69,
	0x73, 0x6b, 0x12, 0x2a, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x6b, 0x55, 0x73, 0x61, 0x67, 0x65, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x44, 0x69,
	0x73, 0x6b, 0x55, 0x73, 0x61, 0x67, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x22, 0x48,
	0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x18,
	0x0a, 0x07, 0x6b, 0x65, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x50,
	0x61, 0x69, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x32, 0xba, 0x01, 0x0a, 0x09, 0x43, 0x41, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x35, 0x0a, 0x06, 0x57, 0x68, 0x6f, 0x41, 0x6d, 0x49, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x11, 0x2e, 0x43, 0x41, 0x57, 0x68, 0x6f, 0x41, 0x6d, 0x49, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x17, 0x2e, 0x43, 0x41, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x12, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69,
	0x72, 0x12, 0x0f, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x09, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x73, 0x22, 0x00, 0x42,
	0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x79,
	0x75, 0x73, 0x68, 0x31, 0x38, 0x30, 0x32, 0x33, 0x2f, 0x4c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x5f, 0x46, 0x79, 0x70, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63,
	0x61, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_carpc_ca_proto_rawDescOnce sync.Once
	file_rpc_carpc_ca_proto_rawDescData = file_rpc_carpc_ca_proto_rawDesc
)

func file_rpc_carpc_ca_proto_rawDescGZIP() []byte {
	file_rpc_carpc_ca_proto_rawDescOnce.Do(func() {
		file_rpc_carpc_ca_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_carpc_ca_proto_rawDescData)
	})
	return file_rpc_carpc_ca_proto_rawDescData
}

var file_rpc_carpc_ca_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_carpc_ca_proto_goTypes = []interface{}{
	(*CAWhoAmIResponse)(nil),       // 0: CAWhoAmIResponse
	(*CAHealthMetricResponse)(nil), // 1: CAHealthMetricResponse
	(*KeyPairRequest)(nil),         // 2: KeyPairRequest
	(*KeyPairs)(nil),               // 3: KeyPairs
	(*emptypb.Empty)(nil),          // 4: google.protobuf.Empty
}
var file_rpc_carpc_ca_proto_depIdxs = []int32{
	4, // 0: CAService.WhoAmI:input_type -> google.protobuf.Empty
	4, // 1: CAService.HealthMetrics:input_type -> google.protobuf.Empty
	2, // 2: CAService.GenerateSSHKeyPair:input_type -> KeyPairRequest
	0, // 3: CAService.WhoAmI:output_type -> CAWhoAmIResponse
	1, // 4: CAService.HealthMetrics:output_type -> CAHealthMetricResponse
	3, // 5: CAService.GenerateSSHKeyPair:output_type -> KeyPairs
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_carpc_ca_proto_init() }
func file_rpc_carpc_ca_proto_init() {
	if File_rpc_carpc_ca_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_carpc_ca_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CAWhoAmIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_carpc_ca_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CAHealthMetricResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_carpc_ca_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_carpc_ca_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPairs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_carpc_ca_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_carpc_ca_proto_goTypes,
		DependencyIndexes: file_rpc_carpc_ca_proto_depIdxs,
		MessageInfos:      file_rpc_carpc_ca_proto_msgTypes,
	}.Build()
	File_rpc_carpc_ca_proto = out.File
	file_rpc_carpc_ca_proto_rawDesc = nil
	file_rpc_carpc_ca_proto_goTypes = nil
	file_rpc_carpc_ca_proto_depIdxs = nil
}
